### ISSUE TITLE
shape not shown in step 4

### ISSUE THREAD

**Issue by xzghx** [material-components/material-components-android-codelabs#43] opened 2019-10-12 15:19 UTC
after folowing all steps from 1 to 4 the output is not what is shown in step 4.
I mean the shap "shr_product_grid_background_shape" is not shoen

**Codelab details 
 - Level ( MDC-10)
 - Language (Java )
 - Link to the codelab at the step with the issue (https://codelabs.developers.google.com/codelabs/mdc-104-java/index.html?index=..%2F..index#3)

**Comment by LakshmanPalli** [comment] 2021-05-31 17:10
Less this issue is still persisting, I hope the google developers look into this issue.
The code for " shr_product_grid_background_shape.xml " is not defined. Thus, the problem arises.
link: https://developers.google.com/codelabs/mdc-104-java?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fmdc-java%23codelab-https%3A%2F%2Fdevelopers.google.com%2Fcodelabs%2Fmdc-104-java#3

**Comment by raajkumars** [comment] 2021-06-04 15:20
Duplicate of #72

**Closed as completed by raajkumars** 2021-06-04 15:20 UTC
