### ISSUE TITLE
Relative Layout is legacy and Constraint Layout should be uses.

### ISSUE THREAD

**Issue by unappropriate** [material-components/material-components-android-codelabs#22] opened 2018-09-14 12:12 UTC
Change Shrine App (Kotlin) to use Constraint Layout instead of Relative Layout.

**Comment by afohrman** [comment] 2018-10-19 18:46
Closing this issue since it's working as intended. We'd be happy to accept a PR if you'd like to contribute.

**Closed by afohrman** 2018-10-19 18:46 UTC
